'use client';

import { useState, useTransition } from 'react';

import { summarizeComparison, type SummarizeResult } from './summary-action';

/**
 * The "Summarize with AI" panel on the compare view (Phase 8).
 *
 * Generation is explicit — a button, not an on-load call — so a shared link never silently bills
 * the provider, and a deploy without a key degrades to a plain message rather than an error. A
 * cached summary passed as `initial` renders immediately with no request. Everything the model
 * produced is grounded in stored facts, and the gaps it names are shown as prominently as the
 * comparisons (BUILD_PLAN.md §16.2).
 */
export function ComparisonSummaryPanel({
  itemIds,
  initial = null,
}: {
  itemIds: string[];
  /** A cached summary the server already found, rendered without a request. */
  initial?: SummarizeResult | null;
}) {
  const [result, setResult] = useState<SummarizeResult | null>(initial);
  const [isPending, startTransition] = useTransition();

  function generate() {
    startTransition(async () => {
      setResult(await summarizeComparison(itemIds));
    });
  }

  const hasSummary = result?.status === 'ok';

  return (
    <section
      className="uc-surface uc-surface--raised flex flex-col gap-3 p-4"
      aria-labelledby="ai-summary-heading"
      data-testid="ai-summary"
    >
      <div className="flex items-center justify-between gap-3">
        <h2 id="ai-summary-heading" className="text-sm font-semibold tracking-tight">
          AI summary
        </h2>
        <button
          type="button"
          onClick={generate}
          disabled={isPending}
          className="uc-button uc-button--secondary uc-focusable text-sm"
        >
          {isPending ? 'Summarizing…' : hasSummary ? 'Regenerate' : 'Summarize with AI'}
        </button>
      </div>

      <p className="text-xs text-[var(--uc-foreground-muted)]">
        A short comparison written only from the facts you saved. It never invents a price, size, or
        material, and it points out what is missing.
      </p>

      {result ? <SummaryBody result={result} /> : null}
    </section>
  );
}

function SummaryBody({ result }: { result: SummarizeResult }) {
  switch (result.status) {
    case 'ok':
      return (
        <div className="flex flex-col gap-3" role="region" aria-label="AI comparison summary">
          <p className="text-sm leading-relaxed">{result.summary.overview}</p>

          {result.summary.points.length > 0 ? (
            <ul className="flex list-disc flex-col gap-1 pl-5 text-sm">
              {result.summary.points.map((point, i) => (
                <li key={i}>{point.text}</li>
              ))}
            </ul>
          ) : null}

          {result.summary.missingData.length > 0 ? (
            <div className="uc-callout uc-callout--warning text-sm">
              <span className="uc-callout__title">What we don&apos;t know</span>
              <ul className="mt-1 flex list-disc flex-col gap-1 pl-5">
                {result.summary.missingData.map((gap, i) => (
                  <li key={i}>{gap}</li>
                ))}
              </ul>
            </div>
          ) : null}

          <p className="text-xs text-[var(--uc-foreground-muted)]">
            Generated by {result.model}
            {result.cached ? ' · from cache' : ''}. A summary is a suggestion — check the table for
            the exact figures.
          </p>
        </div>
      );

    case 'not_configured':
      return (
        <p role="status" className="text-sm text-[var(--uc-foreground-muted)]">
          AI summaries aren&apos;t enabled for this deployment yet.
        </p>
      );

    case 'refused':
      return (
        <p role="status" className="text-sm text-[var(--uc-foreground-muted)]">
          The model declined to summarize these items.
        </p>
      );

    case 'not_enough':
      return (
        <p role="status" className="text-sm text-[var(--uc-foreground-muted)]">
          Pick two to four products to summarize.
        </p>
      );

    case 'error':
      return (
        <p role="alert" className="uc-callout uc-callout--danger text-sm">
          {result.message}
        </p>
      );
  }
}
