import { baseConfig } from '@universal-cart/config/eslint/base';

export default [
  ...baseConfig,
  {
    // Generated by `pnpm db:types`; not hand-edited, so not linted.
    ignores: ['src/database.types.ts'],
  },
];
